### PR TITLE
Fixing Various Open Issues

### LINKED ISSUE #4: Show full name when correct
After you have successfully guessed someone's first name, also show their full name, and perhaps their batch(es).

### LINKED ISSUE #5: Clear guess status on new active person
So it doesn't say "Correct!" or "Wrong :(" before you even type anything.

### LINKED ISSUE #7: Fix or remove title element ID
The `<div>` tag that contains the text "Who is this?" includes an `id` attribute. Unfortunately, it is always set to the value `undefined-title`, because [the code that fills it out](https://github.com/jasonaowen/recurse-faces/blob/028a854422a5dc38b05cc29dcc5e928b8e720edb/src/components/card.js#L16) is looking at the wrong property!

Is the `id` attribute even necessary? I added it as I was learning React. Either fix it or remove it.

### LINKED ISSUE #8: Clear person name on new active person
After guessing & clicking next, the old name (whether it was right or wrong) is currently still being displayed.

### PR DESCRIPTION
**Pull request by botwhytho**
Resolves the issues below. Added dummy test data for if you are only developing the front end.

Resolves #4 
Resolves #5 
Resolves #7 
Resolves #8

### CODE REVIEW

File: src/action_creators.js [hunk 1]
```diff
@@ -11,3 +11,9 @@ export function setActivePerson(person) {
     person
   };
 }
+
+export function clearGuest() {
+    return {
+    type: "CLEARGUEST",
```
Comment (jasonaowen) [inline src/action_creators.js]: Why "Guest"? I would have expected "Guess".

File: src/api.js [hunk 2]
```diff
@@ -1,4 +1,30 @@
...
+//     middle_name: "",
+//     person_id: 1378
+//   },
+//   {
+//     first_name: "Patricia",
+//     image_url: "https://d29xw0ra2h4o4u.cloudfront.net/assets/people/patricia_estridge_150-1e7989ef0d09a7928ea46a199432f412904add6b4defd4855dd80316b8ce6eef.jpg",
+//     last_name: "Estridge",
+//     middle_name: "",
+//     person_id: 587
+//   }
```
Comment (jasonaowen) [inline src/api.js]: Adding placeholder data is a good idea! We probably shouldn't use real people, though. When I was initially developing, I used flower pictures from Wikipedia, but any kinda of non-personal data should be fine.

File: src/api.js [hunk 3]
```diff
@@ -1,4 +1,30 @@
...
+// ]
+// //Comment this out before commits
```
Comment (jasonaowen) [inline src/api.js]: We can probably leave this uncommented, since it's not overwriting or shadowing anything.

File: src/api.js [hunk 4]
```diff
@@ -1,4 +1,30 @@
+// //Static Data for Front-End only testing & development
+// let people = [
```
Comment (jasonaowen) [inline src/api.js]: Maybe "placeholderPeople"?

File: src/api.js [hunk 5]
```diff
@@ -13,4 +39,9 @@ export function getRandomPerson(filter = 'all') {
       return responseJson;
     }
   })
+
+  // // Stub Code to Work on Front-End only by not hitting the API
+  // let data = people[Math.ceil(Math.random() * 100) % people.length]
+  // return new Promise((res, rej) => res(data));
+  // // Comment this out and un-comment actual implementation before commits
```
Comment (jasonaowen) [inline src/api.js]: I wonder if we can have an environment variable to control if this function calls the API or uses the placeholder data? I have no idea how to do that in javascript!

File: src/components/guess.js [hunk 6]
```diff
@@ -4,10 +4,11 @@ import { connect } from 'react-redux';
 class Guess extends Component {
   render() {
     const guess = this.props.guess;
+    console.log(this.props);
     if (guess.get('status') === "correct") {
       return (
           <div className="correct guess">
-            Correct!
+            Correct! Their Full Name is {this.props.person.first_name} {this.props.person.last_name}
```
Comment (jasonaowen) [inline src/components/guess.js]: If you want to stay in the [Immutable.js](https://facebook.github.io/immutable-js/) world, you could say `this.props.person.get('first_name')` - or, better, extract a `person` variable next to the `guess`, and then just `person.get('first_name')`. Then you wouldn't need to `.toJS()` below.

**Comment by jasonaowen** [comment]
Great!
