### PR TITLE
Fixing various issues, typos

### LINKED ISSUE #13: Change person mapStateToProps to immutable

### LINKED ISSUE #14: Next component is triggering default

### PR DESCRIPTION
**Pull request by botwhytho**
Resolve the issues below.

Resolves #14 
Fixed last instance of clearGuest typo, it is clearGuess now
Removed unnecessary debugging console.logs
Resolves #13

### CODE REVIEW

File: src/components/card.js [hunk 1]
```diff
@@ -14,10 +14,10 @@ class Card extends Component {
     const person = this.props.person;
     return (
       <div className="card">
-        <div className="person-title" id={person.get('person_id') + "-title"}>
+        <div className="person-title" id={person.getIn(['0','person_id']) + "-title"}>
           Who is this?
         </div>
-        <img src={person.get('image_url')}
+        <img src={person.getIn(['0','image_url'])}
```
Comment (jasonaowen) [inline src/components/card.js]: I think this will break in production, since the API does not yet return an array. Can you please remove this commit from the PR?

**Comment by jasonaowen** [comment]
Awesome! Thank you.
